
debian/61-autopilot3-uinput.rules /lib/udev/rules.d
usr/bin/autopilot3 /usr/bin/
usr/bin/autopilot3-sandbox-run /usr/bin/
usr/lib/python3*/*/autopilot*.egg-info
usr/lib/python3*/*/autopilot/*.py
usr/lib/python3*/*/autopilot/application/*.py
usr/lib/python3*/*/autopilot/display/*.py
usr/lib/python3*/*/autopilot/input/*.py
usr/lib/python3*/*/autopilot/introspection/*.py
usr/lib/python3*/*/autopilot/matchers/*.py
usr/lib/python3*/*/autopilot/process/*.py
